add `@typescript-eslint/parser` to devDependencies (#105)
Currently, `trunk check` doesn't work on freshly cloned and `yarn
install`ed repos due to eslint not being able to find the package:

```
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.yaml » plugin:@typescript-eslint/recommended-requiring-type-checking » ./configs/base': Cannot find module '@typescript-eslint/parser'
```

This fixes that.